POST http://localhost:8080/api/v1/blog/create-blog
Content-Type: application/json

{
    "title":"An idea can change your life",
    "description":"La Belle Dame sans Merci, The Beautiful Lady Without Mercy is a ballad produced by the English poet John Keats in 1819. The title was derived from the title of a 15th-century poem by Alain Chartier called La Belle Dame sans Mercy La Belle Dame sans Merci, The Beautiful Lady Without Mercy is a ballad produced by the English poet John Keats in 1819. The title was derived from the title of a 15th-century poem by Alain Chartier called La Belle Dame sans Mercy",

    "user":"6453d64e2cff2d8e8178e724"
}